# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f958c94b6b4cdbf129e5db21e247a7c2f5f53a45dd5ec541614d011b503233dc7335a25f7c6eed0472fd1b4ad6202c8581b0135124ec3fc18d32a93e00650060

test:
  secret_key_base: eb45ccd7839f03960ffa767666369843cf2337a0c8c03c57b6ba7ba2085f384e6ab306b69ef043f0e7188595b033062e07ee24210ca827d27bc608044c7282ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
